name: requirements-check

on:
  push:
    branches:


jobs:
  my_job:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python environment
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'
        architecture: 'x64'
        
    - name: Install pylint
      run: |
        pip install pylint
        
    - name: Create pylintrc file
      run: |
        pylint --generate-rcfile > .pylintrc
        
    - name: Linter test
      run: |
        pylint --disable=all $(git ls-files '*.py')
